run:
  timeout: 5m

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: false
  revive:
    min-confidence: 0
  dupl:
    threshold: 100
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style

issues:
  exclude:
    - "unused-parameter: parameter '\\w+' seems to be unused, consider removing or renaming it as _"

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
  - bodyclose
  # - depguard
  - dogsled
  - dupl
  - errcheck
  - exportloopref
  # - funlen
  # - gochecknoglobals
  - gochecknoinits
  # - gocognit
  - goconst
  # - godox
  # - gocritic
  - gocyclo
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - prealloc
  - revive
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  # - wsl
