project_name: arrai
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod tidy

build:
  binary: arrai
  id: arrai
  main: ./cmd/arrai
  ldflags:
    - -s -w -X main.Version=v{{.Version}}
    - -X main.GitTags={{.Tag}}
    - -X main.GitCommit={{.ShortCommit}}
    - -X main.GitFullCommit={{.FullCommit}}
    - -X main.BuildDate={{.Date}}
    - -X main.BuildOS={{.Os}}
    - -X main.BuildArch={{.Arch}}
    - -s -w -X "main.GoVersion={{.Env.GOVERSION}}"
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
    - 386
  goarm:
    - 7
  ignore:
    - goos: darwin
      goarch: 386

archives:
- id: "arrai"
  builds: ['arrai']
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
  files:
    - README.md
    - LICENSE

checksum:
  name_template: '{{.ProjectName}}_v{{.Version}}_checksums.txt'
snapshot:
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
