name: Docker

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: docker.io/anzbank/arrai
          tag_with_ref: true
          add_git_labels: true
          tags: latest
          labels: org.opencontainers.image.revision=${{ github.sha }},org.opencontainers.image.url=https://arr.ai