name: Docker

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/anzbank/arrai
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=sha,prefix=,format=long
          labels: |
            org.opencontainers.image.url=https://arr.ai

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker container image
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test container image
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          config: container-structure-tests.yaml

      - name: Login to DockerHub
        # only attempt to push if we are in the open source repo that has credentials, and there's been a push, not merely a pull request.
        if: github.repository == 'arr-ai/arrai' && github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push docker container image
        # only attempt to push if we are in the open source repo that has credentials, and there's been a push, not merely a pull request.
        if: github.repository == 'arr-ai/arrai' && github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
