name: Docs

on: [pull_request]

env:
  NPM_CONFIG_REGISTRY: ${{ vars.NPM_CONFIG_REGISTRY }}

jobs:
  build:
    name: Build Docusaurus site
    runs-on: ${{ vars.RUNNER_UBUNTU && fromJSON(vars.RUNNER_UBUNTU) || 'ubuntu-latest' }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Uses Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install yarn
        run: npm install -g yarn

      - name: yarn build docs
        working-directory: docs
        run: |
          # switch registry in lock file
          if [ -n "${{ env.NPM_CONFIG_REGISTRY }}" ]; then
            sed -i'.bak' 's#https://registry.npmjs.org#${{ env.NPM_CONFIG_REGISTRY }}#' yarn.lock
            sed -i'.bak' 's#https://registry.yarnpkg.com#${{ env.NPM_CONFIG_REGISTRY }}#' yarn.lock
            rm yarn.lock.bak
          fi

          yarn install && yarn build
