name: Docs

on: [pull_request]

jobs:
  build:
    name: Build Docusaurus site
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Uses Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install yarn
        run: npm install -g yarn

      - name: yarn build docs
        working-directory: docs
        run: yarn install && yarn build
